owner: saizaax
repo: upptime

sites:
  - name: saizaax.dev
    url: https://saizaax.dev/
  - name: uncos.saizaax.dev
    url: https://uncos.saizaax.dev/
  - name: pizza.saizaax.dev
    url: https://pizza.saizaax.dev/
  - name: xanity.saizaax.dev
    url: https://xanity.saizaax.dev/
  - name: schedule.saizaax.dev
    url: https://schedule.saizaax.dev/
  - name: docstorage.saizaax.dev
    url: https://docstorage.saizaax.dev/
