owner: saizaax # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: saizaax.xyz
    url: https://saizaax.xyz/
  - name: uncos.saizaax.xyz
    url: https://uncos.saizaax.xyz/
  - name: pizza.saizaax.xyz
    url: https://pizza.saizaax.xyz/
  - name: xanity.saizaax.xyz
    url: https://xanity.saizaax.xyz/
  - name: schedule.saizaax.xyz
    url: https://schedule.saizaax.xyz/
    
